# Copyright (c) 2023 Georgios Alexopoulos
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xpushare-device-plugin
  namespace: xpushare-system
spec:
  selector:
    matchLabels:
      name: xpushare-device-plugin
  template:
    metadata:
      labels:
        name: xpushare-device-plugin
    spec:
      priorityClassName: system-node-critical
      containers:
      - name: xpushare-lib
        image: registry.cn-hangzhou.aliyuncs.com/xpushare/xpushare-lib:libxpushare-v0.1-8c2f5b90
        command:
        - sleep
        - infinity
        lifecycle:
          postStart:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - "test -f /host-var-run-xpushare/libxpushare.so || touch /host-var-run-xpushare/libxpushare.so && mount -v --bind /libxpushare.so /host-var-run-xpushare/libxpushare.so"
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - "umount -v /host-var-run-xpushare/libxpushare.so && rm /host-var-run-xpushare/libxpushare.so"
        securityContext:
          # Necessary for mounts to work.
          privileged: true
        volumeMounts:
        - mountPath: /host-var-run-xpushare
          name: host-var-run-xpushare
          # A bidirectional mount ensures that mount points also show up on the
          # host. We need this because xpushare-device-plugin modifies the specs
          # of the Pods that request xpushare virtual GPUs and adds a hostPath
          # mount for /var/run/xpushare/libxpushare.so
          mountPropagation: Bidirectional
      - name: xpushare-device-plugin
        image: registry.cn-hangzhou.aliyuncs.com/xpushare/xpushare-device-plugin:xpushare-device-plugin-v0.1-8c2f5b90
        imagePullPolicy: IfNotPresent
        env:
        - name: ASCEND_VISIBLE_DEVICES
          value: "0,1"
        - name: XPUSHARE_VIRTUAL_DEVICES
          value: "10"
        - name: XPUSHARE_ASCEND_MIN_DRIVER_VERSION
          value: "25.5.0"
        securityContext:
          privileged: true
        volumeMounts:
          - name: device-plugin-socket
            mountPath: /var/lib/kubelet/device-plugins
        resources:
          limits:
            nvidia.com/gpu: 32
      volumes:
        - name: host-var-run-xpushare
          hostPath:
            path: /var/run/xpushare
            type: DirectoryOrCreate
        - name: device-plugin-socket
          hostPath:
            path: /var/lib/kubelet/device-plugins
      tolerations:
      # In some cases, GPU nodes have an nvidia.com/gpu taint to run only
      # GPU workloads. Tolerate that taint.
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
