# Copyright (c) 2023 Georgios Alexopoulos
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xpushare-scheduler
  namespace: xpushare-system
spec:
  selector:
    matchLabels:
      name: xpushare-scheduler
  template:
    metadata:
      labels:
        name: xpushare-scheduler
    spec:
      serviceAccountName: xpushare-scheduler
      priorityClassName: system-node-critical
      containers:
      - name: xpushare-scheduler
        image: registry.cn-hangzhou.aliyuncs.com/xpushare/xpushare-scheduler:xpushare-scheduler-v0.1-8c2f5b90
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: xpushare-socket-directory
            mountPath: /var/run/xpushare
        env:
        - name: XPUSHARE_DEBUG
          value: "1"
        - name: XPUSHARE_QUOTA_CARRYOVER_PERCENT
          value: "0"
      volumes:
        - name: xpushare-socket-directory
          hostPath:
            path: /var/run/xpushare
            type: DirectoryOrCreate
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
